# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'icsApp' do

platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'
pod "MagicalRecord"

end

target 'icsAppTests' do

end

